// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

public interface AllocateDataNodesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuyiccc.hellodfs.namenode.rpc.AllocateDataNodesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string dataNodes = 1;</code>
   */
  java.lang.String getDataNodes();
  /**
   * <code>optional string dataNodes = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataNodesBytes();
}
