// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

public interface FetchEditsLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuyiccc.hellodfs.namenode.rpc.FetchEditsLogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 syncTxId = 1;</code>
   */
  long getSyncTxId();
}
