// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

public interface GetDataNodeForFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuyiccc.hellodfs.namenode.rpc.GetDataNodeForFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string dataNodeInfo = 1;</code>
   */
  java.lang.String getDataNodeInfo();
  /**
   * <code>optional string dataNodeInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataNodeInfoBytes();
}
