// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

public interface HeartBeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuyiccc.hellodfs.namenode.rpc.HeartBeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 status = 1;</code>
   */
  int getStatus();
}
