// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

public final class NameNodeRpcModel {
  private NameNodeRpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_CreateFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_CreateFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_CreateFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_CreateFileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_AllocateDataNodesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_AllocateDataNodesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_AllocateDataNodesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_AllocateDataNodesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_InformReplicaReceivedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_InformReplicaReceivedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_InformReplicaReceivedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_InformReplicaReceivedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReportAllStorageInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReportAllStorageInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReportAllStorageInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReportAllStorageInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026NameNodeRpcModel.proto\022!com.wuyiccc.he" +
      "llodfs.namenode.rpc\"@\n\017RegisterRequest\022\n" +
      "\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\022\017\n\007nioPort\030" +
      "\003 \001(\005\"\"\n\020RegisterResponse\022\016\n\006status\030\001 \001(" +
      "\005\"A\n\020HeartBeatRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hos" +
      "tname\030\002 \001(\t\022\017\n\007nioPort\030\003 \001(\005\"5\n\021HeartBea" +
      "tResponse\022\016\n\006status\030\001 \001(\005\022\020\n\010commands\030\002 " +
      "\001(\t\"\034\n\014MkdirRequest\022\014\n\004path\030\001 \001(\t\"\037\n\rMkd" +
      "irResponse\022\016\n\006status\030\001 \001(\005\"\037\n\017ShutdownRe" +
      "quest\022\014\n\004code\030\001 \001(\005\"\"\n\020ShutdownResponse\022",
      "\016\n\006status\030\001 \001(\005\"(\n\024FetchEditsLogRequest\022" +
      "\020\n\010syncTxId\030\001 \001(\003\")\n\025FetchEditsLogRespon" +
      "se\022\020\n\010editsLog\030\001 \001(\t\"+\n\033UpdateCheckpoint" +
      "TxIdRequest\022\014\n\004txId\030\001 \001(\003\".\n\034UpdateCheck" +
      "pointTxIdResponse\022\016\n\006status\030\001 \001(\005\"%\n\021Cre" +
      "ateFileRequest\022\020\n\010filename\030\001 \001(\t\"$\n\022Crea" +
      "teFileResponse\022\016\n\006status\030\001 \001(\005\">\n\030Alloca" +
      "teDataNodesRequest\022\020\n\010filename\030\001 \001(\t\022\020\n\010" +
      "fileSize\030\002 \001(\003\".\n\031AllocateDataNodesRespo" +
      "nse\022\021\n\tdataNodes\030\001 \001(\t\"N\n\034InformReplicaR",
      "eceivedRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002" +
      " \001(\t\022\020\n\010filename\030\003 \001(\t\"/\n\035InformReplicaR" +
      "eceivedResponse\022\016\n\006status\030\001 \001(\005\"m\n\033Repor" +
      "tAllStorageInfoRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010ho" +
      "stname\030\002 \001(\t\022\030\n\020filenameListJson\030\003 \001(\t\022\026" +
      "\n\016storedDataSize\030\004 \001(\003\".\n\034ReportAllStora" +
      "geInfoResponse\022\016\n\006status\030\001 \001(\005\"Q\n!Choose" +
      "DataNodeFromReplicasRequest\022\020\n\010filename\030" +
      "\001 \001(\t\022\032\n\022excludedDataNodeId\030\002 \001(\t\":\n\"Cho" +
      "oseDataNodeFromReplicasResponse\022\024\n\014dataN",
      "odeInfo\030\001 \001(\t\"[\n\031ReallocateDataNodeReque" +
      "st\022\020\n\010filename\030\001 \001(\t\022\020\n\010fileSize\030\002 \001(\003\022\032" +
      "\n\022excludedDataNodeId\030\003 \001(\t\"2\n\032Reallocate" +
      "DataNodeResponse\022\024\n\014dataNodeInfo\030\001 \001(\tB=" +
      "\n\'com.wuyiccc.hellodfs.namenode.rpc.mode" +
      "lB\020NameNodeRpcModelP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "NioPort", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "NioPort", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatResponse_descriptor,
        new java.lang.String[] { "Status", "Commands", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownRequest_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogRequest_descriptor,
        new java.lang.String[] { "SyncTxId", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogResponse_descriptor,
        new java.lang.String[] { "EditsLog", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdRequest_descriptor,
        new java.lang.String[] { "TxId", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_CreateFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_CreateFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_CreateFileRequest_descriptor,
        new java.lang.String[] { "Filename", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_CreateFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_CreateFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_CreateFileResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_AllocateDataNodesRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_AllocateDataNodesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_AllocateDataNodesRequest_descriptor,
        new java.lang.String[] { "Filename", "FileSize", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_AllocateDataNodesResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_AllocateDataNodesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_AllocateDataNodesResponse_descriptor,
        new java.lang.String[] { "DataNodes", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_InformReplicaReceivedRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_InformReplicaReceivedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_InformReplicaReceivedRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "Filename", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_InformReplicaReceivedResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_InformReplicaReceivedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_InformReplicaReceivedResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReportAllStorageInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReportAllStorageInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReportAllStorageInfoRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "FilenameListJson", "StoredDataSize", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReportAllStorageInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReportAllStorageInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReportAllStorageInfoResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_ChooseDataNodeFromReplicasRequest_descriptor,
        new java.lang.String[] { "Filename", "ExcludedDataNodeId", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_ChooseDataNodeFromReplicasResponse_descriptor,
        new java.lang.String[] { "DataNodeInfo", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeRequest_descriptor,
        new java.lang.String[] { "Filename", "FileSize", "ExcludedDataNodeId", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeResponse_descriptor,
        new java.lang.String[] { "DataNodeInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
