// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

public final class NameNodeRpcModel {
  private NameNodeRpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026NameNodeRpcModel.proto\022!com.wuyiccc.he" +
      "llodfs.namenode.rpc\"/\n\017RegisterRequest\022\n" +
      "\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\"\"\n\020Register" +
      "Response\022\016\n\006status\030\001 \001(\005\"0\n\020HeartBeatReq" +
      "uest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\"#\n\021He" +
      "artBeatResponse\022\016\n\006status\030\001 \001(\005\"\034\n\014Mkdir" +
      "Request\022\014\n\004path\030\001 \001(\t\"\037\n\rMkdirResponse\022\016" +
      "\n\006status\030\001 \001(\005\"\037\n\017ShutdownRequest\022\014\n\004cod" +
      "e\030\001 \001(\005\"\"\n\020ShutdownResponse\022\016\n\006status\030\001 " +
      "\001(\005\"$\n\024FetchEditsLogRequest\022\014\n\004code\030\001 \001(",
      "\005\")\n\025FetchEditsLogResponse\022\020\n\010editsLog\030\001" +
      " \001(\tB=\n\'com.wuyiccc.hellodfs.namenode.rp" +
      "c.modelB\020NameNodeRpcModelP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_RegisterResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_HeartBeatResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_MkdirResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownRequest_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_ShutdownResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogRequest_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wuyiccc_hellodfs_namenode_rpc_FetchEditsLogResponse_descriptor,
        new java.lang.String[] { "EditsLog", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
