// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

/**
 * Protobuf type {@code com.wuyiccc.hellodfs.namenode.rpc.ReallocateDataNodeResponse}
 */
public  final class ReallocateDataNodeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.wuyiccc.hellodfs.namenode.rpc.ReallocateDataNodeResponse)
    ReallocateDataNodeResponseOrBuilder {
  // Use ReallocateDataNodeResponse.newBuilder() to construct.
  private ReallocateDataNodeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReallocateDataNodeResponse() {
    dataNodeInfo_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ReallocateDataNodeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            dataNodeInfo_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse.class, com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse.Builder.class);
  }

  public static final int DATANODEINFO_FIELD_NUMBER = 1;
  private volatile java.lang.Object dataNodeInfo_;
  /**
   * <code>optional string dataNodeInfo = 1;</code>
   */
  public java.lang.String getDataNodeInfo() {
    java.lang.Object ref = dataNodeInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataNodeInfo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string dataNodeInfo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDataNodeInfoBytes() {
    java.lang.Object ref = dataNodeInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataNodeInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDataNodeInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataNodeInfo_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDataNodeInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataNodeInfo_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse)) {
      return super.equals(obj);
    }
    com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse other = (com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse) obj;

    boolean result = true;
    result = result && getDataNodeInfo()
        .equals(other.getDataNodeInfo());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + DATANODEINFO_FIELD_NUMBER;
    hash = (53 * hash) + getDataNodeInfo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.wuyiccc.hellodfs.namenode.rpc.ReallocateDataNodeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.wuyiccc.hellodfs.namenode.rpc.ReallocateDataNodeResponse)
      com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse.class, com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse.Builder.class);
    }

    // Construct using com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dataNodeInfo_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_wuyiccc_hellodfs_namenode_rpc_ReallocateDataNodeResponse_descriptor;
    }

    public com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse getDefaultInstanceForType() {
      return com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse.getDefaultInstance();
    }

    public com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse build() {
      com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse buildPartial() {
      com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse result = new com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse(this);
      result.dataNodeInfo_ = dataNodeInfo_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse) {
        return mergeFrom((com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse other) {
      if (other == com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse.getDefaultInstance()) return this;
      if (!other.getDataNodeInfo().isEmpty()) {
        dataNodeInfo_ = other.dataNodeInfo_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object dataNodeInfo_ = "";
    /**
     * <code>optional string dataNodeInfo = 1;</code>
     */
    public java.lang.String getDataNodeInfo() {
      java.lang.Object ref = dataNodeInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataNodeInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string dataNodeInfo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataNodeInfoBytes() {
      java.lang.Object ref = dataNodeInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataNodeInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string dataNodeInfo = 1;</code>
     */
    public Builder setDataNodeInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataNodeInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string dataNodeInfo = 1;</code>
     */
    public Builder clearDataNodeInfo() {
      
      dataNodeInfo_ = getDefaultInstance().getDataNodeInfo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string dataNodeInfo = 1;</code>
     */
    public Builder setDataNodeInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataNodeInfo_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.wuyiccc.hellodfs.namenode.rpc.ReallocateDataNodeResponse)
  }

  // @@protoc_insertion_point(class_scope:com.wuyiccc.hellodfs.namenode.rpc.ReallocateDataNodeResponse)
  private static final com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse();
  }

  public static com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReallocateDataNodeResponse>
      PARSER = new com.google.protobuf.AbstractParser<ReallocateDataNodeResponse>() {
    public ReallocateDataNodeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReallocateDataNodeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReallocateDataNodeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReallocateDataNodeResponse> getParserForType() {
    return PARSER;
  }

  public com.wuyiccc.hellodfs.namenode.rpc.model.ReallocateDataNodeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

