// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

public interface ReallocateDataNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuyiccc.hellodfs.namenode.rpc.ReallocateDataNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string filename = 1;</code>
   */
  java.lang.String getFilename();
  /**
   * <code>optional string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>optional int64 fileSize = 2;</code>
   */
  long getFileSize();

  /**
   * <code>optional string excludedDataNode = 3;</code>
   */
  java.lang.String getExcludedDataNode();
  /**
   * <code>optional string excludedDataNode = 3;</code>
   */
  com.google.protobuf.ByteString
      getExcludedDataNodeBytes();
}
