// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

public interface RebalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuyiccc.hellodfs.namenode.rpc.RebalanceRequest)
    com.google.protobuf.MessageOrBuilder {
}
