// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

public interface UpdateCheckpointTxIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wuyiccc.hellodfs.namenode.rpc.UpdateCheckpointTxIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 txId = 1;</code>
   */
  long getTxId();
}
