// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.wuyiccc.hellodfs.namenode.rpc.model;

/**
 * Protobuf type {@code com.wuyiccc.hellodfs.namenode.rpc.UpdateCheckpointTxIdRequest}
 */
public  final class UpdateCheckpointTxIdRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.wuyiccc.hellodfs.namenode.rpc.UpdateCheckpointTxIdRequest)
    UpdateCheckpointTxIdRequestOrBuilder {
  // Use UpdateCheckpointTxIdRequest.newBuilder() to construct.
  private UpdateCheckpointTxIdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateCheckpointTxIdRequest() {
    txId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UpdateCheckpointTxIdRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            txId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest.class, com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest.Builder.class);
  }

  public static final int TXID_FIELD_NUMBER = 1;
  private long txId_;
  /**
   * <code>optional int64 txId = 1;</code>
   */
  public long getTxId() {
    return txId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (txId_ != 0L) {
      output.writeInt64(1, txId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (txId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, txId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest)) {
      return super.equals(obj);
    }
    com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest other = (com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest) obj;

    boolean result = true;
    result = result && (getTxId()
        == other.getTxId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TXID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTxId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.wuyiccc.hellodfs.namenode.rpc.UpdateCheckpointTxIdRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.wuyiccc.hellodfs.namenode.rpc.UpdateCheckpointTxIdRequest)
      com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest.class, com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest.Builder.class);
    }

    // Construct using com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      txId_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.internal_static_com_wuyiccc_hellodfs_namenode_rpc_UpdateCheckpointTxIdRequest_descriptor;
    }

    public com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest getDefaultInstanceForType() {
      return com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest.getDefaultInstance();
    }

    public com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest build() {
      com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest buildPartial() {
      com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest result = new com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest(this);
      result.txId_ = txId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest) {
        return mergeFrom((com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest other) {
      if (other == com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest.getDefaultInstance()) return this;
      if (other.getTxId() != 0L) {
        setTxId(other.getTxId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long txId_ ;
    /**
     * <code>optional int64 txId = 1;</code>
     */
    public long getTxId() {
      return txId_;
    }
    /**
     * <code>optional int64 txId = 1;</code>
     */
    public Builder setTxId(long value) {
      
      txId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 txId = 1;</code>
     */
    public Builder clearTxId() {
      
      txId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.wuyiccc.hellodfs.namenode.rpc.UpdateCheckpointTxIdRequest)
  }

  // @@protoc_insertion_point(class_scope:com.wuyiccc.hellodfs.namenode.rpc.UpdateCheckpointTxIdRequest)
  private static final com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest();
  }

  public static com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateCheckpointTxIdRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateCheckpointTxIdRequest>() {
    public UpdateCheckpointTxIdRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateCheckpointTxIdRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateCheckpointTxIdRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateCheckpointTxIdRequest> getParserForType() {
    return PARSER;
  }

  public com.wuyiccc.hellodfs.namenode.rpc.model.UpdateCheckpointTxIdRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

