server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 # tomcat上传文件限制



spring:
  profiles:
    active: local
  application:
    name: hellodfs-admin

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.134:3306/hellodfs-admin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 123
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1


# tkmybatis配置
mapper:
  mappers: com.wuyiccc.hellodfs.admin.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
mybatis:
  type-aliases-package: com.wuyiccc.hellodfs.admin.common.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true