// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package com.wuyiccc.hellodfs.namenode.rpc.service;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022!com.wuyiccc.h" +
      "ellodfs.namenode.rpc\032\026NameNodeRpcModel.p" +
      "roto2\376\001\n\017NameNodeService\022s\n\010register\0222.c" +
      "om.wuyiccc.hellodfs.namenode.rpc.Registe" +
      "rRequest\0323.com.wuyiccc.hellodfs.namenode" +
      ".rpc.RegisterResponse\022v\n\theartBeat\0223.com" +
      ".wuyiccc.hellodfs.namenode.rpc.HeartBeat" +
      "Request\0324.com.wuyiccc.hellodfs.namenode." +
      "rpc.HeartBeatResponseB=\n)com.wuyiccc.hel" +
      "lodfs.namenode.rpc.serviceB\016NameNodeServ",
      "erP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor(),
        }, assigner);
    com.wuyiccc.hellodfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
